on:
    push:
        branches: main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
              
            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Install Dependencies
              run: composer install --ignore-platform-req=ext-sodium

            # - name: Migrate DB
            #   run: |
            #     php artisan migrate --force

              env:
                APP_ENV: production
                FIREBASE_PROJECT=${{ secrets.FIREBASE_PROJECT }}
                FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }}
                FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}
                VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
                VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}
