on:
    push:
        branches: main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                
            - name: Setup PostgreSQL
              uses: Harmon758/postgresql-action@v1.0.0
              with:
                postgresql version: default
                postgresql db: verceldb
                postgresql user: default 
                postgresql password: iVxgKq5UHE7Y

            - name: Enable PostgreSQL Service
              run: sudo systemctl start postgresql.service
              
            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Install Dependencies
              run: composer install

            - name: Migrate DB
              run: |
                php artisan migrate --force
              
            - name: Enable write to storage
              run: chmod -R 777 /var/task/user/storage/

            - name: Make app folder
              run: mkdir /var/task/user/storage/app
            
            - name: Enable write to storage/app
              run: chmod -R 777 /var/task/user/storage/app

            - name: Clear Cache
              run: |
                php artisan config:cache

            - name: Clear Cache
              run: |
                php artisan optimize:clear

              env:
                APP_ENV: production
                # DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
                # DB_HOST: ${{ secrets.DB_HOST }}
                # DB_PORT: 3306
                # DB_DATABASE: ${{ secrets.DB_DATABASE }}
                # DB_USERNAME: ${{ secrets.DB_USERNAME }}
                # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                # MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt

                DB_CONNECTION: ${{ secrests.DB_CONNECTION }}
                DB_URL: ${{ secrests.DB_URL }}
                DB_HOST: ${{ secrests.DB_HOST }}
                DB_PORT: ${{ secrests.DB_PORT }}
                DB_DATABASE: ${{ secrests.DB_DATABASE }}
                DB_USERNAME: ${{ secrests.DB_USERNAME }}
                DB_PASSWORD: ${{ secrests.DB_PASSWORD }}
