on:
    push:
        branches: main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'

            - name: Enable PostgreSQL Service
              run: sudo apt-get install php-pgsql
              
            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Install Dependencies
              run: composer install

            - name: Migrate DB
              run: |
                php artisan migrate --force
            - name: Change 1st mode
              run: chmod -R 777 /var/task/user/public/uploads
            - name: Change 1st mode
              run: chmod -R 777 /var/task/user/public/db/database.sqlite
            
            - name: Run script
              run: chmod +x script.sh
            - name: Run script
              run: ./script.sh

              env:
                APP_ENV: production
                DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
                DB_DATABASE: ${{ secrets.DB_DATABASE }}
