on:
    push:
        branches: main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'

            - name: Install Vercel CLI
              run: npm install

            - name: Install Dependencies
              run: composer install

            - name: Migrate DB
              run: |
                php artisan migrate --force
              env:
                APP_ENV: production
                DB_CONNECTION: sqlite
                # DB_HOST: ${{ secrets.DB_HOST }}
                # DB_PORT: 3306
                # DB_DATABASE: ${{ secrets.DB_DATABASE }}
                # DB_USERNAME: ${{ secrets.DB_USERNAME }}
                # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                # MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt
